# Site settings
title: "Die Ursuppe" 
email: post@jakobvicari.de
description: "Eine Live-Reportage über Urzeitkrebse. Für Sie im Moment des Aufrufs aus Sensordaten generiert und serviert."
baseurl: "/ursuppe/" # the subpath of your site, e.g. /blog/
url: "http://sensorjournalismus.de" # the base hostname & protocol for your site
twitter_username: roboterreporter
github_username:  drjakob

# Build settings
markdown: kramdown
